package v0id.vsb.util;

public enum EnumGuiType
{
    BACKPACK,
    BACKPACK_NESTED,
    WORN_BACKPACK,
    WORN_BACKPACK_UPGRADES,
    BACKPACK_UPGRADES,
    UPGRADE,
    FILTER,
    UPGRADE_ENDER_STORAGE,
    ENDER_CHEST,
    UPGRADE_CRAFTING
}
